### ISSUE TITLE
Eclipseにプラグイン導入後Maven実行でエラー

### ISSUE THREAD

**Issue by nagatomo-o** [cypher256/pleiades.io#108]
## 概要など

Pleiades All in Oneを使用せず Eclipse IDE for Java Developers(2022-03) に Pleiades日本語化プラグインをインストールして使用しようとしています。
MavenプロジェクトをインポートしてMaven実行を行うとエラーとなってしまいます。
Eclipse自体やプラグインの競合の可能性も探っていますが原因がわからない状況です。

試したところ
- Pleiades All in One (2022-06)では起きない
- Pleiades日本語化プラグインをインストせず Eclipse だけでは起きない
- Maven complie や maven install でも同様なエラーが発生する

## バージョン

- OS : Windows 10
- eclipse : eclipse-java-2022-03-R-win32-x86_64
- pleiadesプラグイン : 2022.05.15
- Sccopでopenjdk11とMavenをインストールしています

## 手順

1. Eclipse公式から eclipse-java-2022-03-R-win32-x86_64をダウンロード
2. Zipファイルを 7ZipでC:\eclipse-java\eclipse に解凍
3. pleiades-win.zipをダウンロードして解凍
4. pleiades-win\setup.exe を起動
5. C:\eclipse-java\eclipse\eclipse.exe を指定して 日本語化実行
6. C:\eclipse-java\eclipse\eclipse.exe -clean.cmd でEclipse起動
7. ワークスペースは空のフォルダ C:\Users\<User>\eclipse-workspace としました
8. プロジェクト > インポート> Gitからプロジェクト > (なんでもよいのですが) https://github.com/jenkins-docs/simple-java-maven-app をインポート
9. Mavenプロジェクト 右クリック > Maven > maven clean 

### エラー画面

![20220520-01](https://user-images.githubusercontent.com/105902792/169453447-a26b1320-25e9-4c98-8bdc-5d9632e3aeb8.png)

### エラー内容

```
org.codehaus.plexus.classworlds.launcher.ConfigurationException: Unhandled configuration (3): Load C:\eclipse-java\eclipse\plugins\org.eclipse.m2e.maven.runtime_1.18.3.20220227-1319\
	at org.codehaus.plexus.classworlds.launcher.ConfigurationParser.parse(ConfigurationParser.java:308)
	at org.codehaus.plexus.classworlds.launcher.Configurator.configure(Configurator.java:133)
	at org.codehaus.plexus.classworlds.launcher.Launcher.configure(Launcher.java:127)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:400)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

### pleiades.log
C:\eclipse-java\eclipse\configuration\jp.sourceforge.mergedoc.pleiades\pleiades.log
```
INFO  13:26:30.838 [ForkJoinPool-1-worker-3] (LauncherTransformer) Pleiades AOP 起動トランスフォーマーを開始します。LauncherEclipseTransformer 0.043 秒
INFO  13:26:30.838 [ForkJoinPool-2-worker-1] (UpdateDetector) ファイル更新最終時刻 (前回): 2022-05-20 13:19:44
INFO  13:26:30.759 [ForkJoinPool-1-worker-2] (LauncherEclipseTransformer) Eclipse version [4.23] year [2022] buildId [4.23.0.I20220308-0310]
INFO  13:26:30.843 [ForkJoinPool-1-worker-2] (LauncherEclipseTransformer) スプラッシュ画像
![20220520-01](https://user-images.githubusercontent.com/105902792/169453289-1f5bae86-ea8b-45d2-9d3e-a6367276bbf0.png)
: splash2022.bmp - C:\eclipse-java\eclipse\dropins\MergeDoc\eclipse\plugins\jp.sourceforge.mergedoc.pleiades\conf\images
INFO  13:26:30.898 [ForkJoinPool-2-worker-1] (UpdateDetector) ファイル更新最終時刻 (今回): 2022-05-20 13:19:44
INFO  13:26:30.972 [ForkJoinPool-1-worker-4] (PleiadesConfig) Pleiades 構成ファイルをロードしました。pleiades-config.xml
INFO  13:26:31.088 [ForkJoinPool-1-worker-4] (LauncherTransformer) -clean 元引数:true 確定後:true
INFO  13:26:31.117 [ForkJoinPool-1-worker-4] (CacheFilez) すべてのキャッシュ・ファイルをクリアしました。
INFO  13:26:31.118 [ForkJoinPool-1-worker-4] (TransformedClassCache) transformed-class.cache が存在しません。
INFO  13:26:31.120 [ForkJoinPool-1-worker-4] (ExcludeClassNameCache) exclude-class.list が存在しません。
INFO  13:26:31.120 [ForkJoinPool-1-worker-4] (LauncherTransformer) Pleiades AOP 翻訳トランスフォーマーを開始します。
INFO  13:26:40.458 [Framework Event Dispatche] (LauncherEclipseTransformer) 起動時のトランスフォーム: org.eclipse.ui.internal.Workbench
INFO  13:26:47.189 [main] (LauncherEclipseTransformer) 起動時のトランスフォーム: org.eclipse.ui.application.WorkbenchAdvisor
INFO  13:26:48.892 [main] (LauncherEclipseTransformer) 起動時のトランスフォーム: org.eclipse.core.resources.ResourcesPlugin
INFO  13:27:05.117 [ForkJoinPool-1-worker-1] (Analyses) Eclipse 起動完了 - 起動時間: 34.033 秒。-clean:true
```

### Workspace .log

C:\Users\<User>\eclipse-workspace\.metadata\.log

```
!SESSION 2022-05-20 13:26:31.084 -----------------------------------------------
eclipse.buildId=4.23.0.I20220308-0310
java.version=17.0.2
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ja_JP
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product -clean

!ENTRY org.eclipse.egit.ui 2 0 2022-05-20 13:27:05.439
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\<User>'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.
```

### 環境変数

![20220520-02](https://user-images.githubusercontent.com/105902792/169454389-abb29082-a49f-49b7-92fb-cbb550e3c011.png)

**Comment by cypher256** [comment]
詳細ありがとうございます。
Maven プラグインの設定ファイルの読み込みに NLS.bind という国際化用 API が使われているのが原因でした。
Pleiades は NLS.bind を AOP して翻訳していますが、該当箇所を除外するようにしました。

さきほど Pleiades 日本語化プラグイン 2022.05.20 をリリースしたので、ご確認ください。
Pleiades All in One のリリースはありません。

**Comment by nagatomo-o** [comment]
早々の対応ありがとうございます。
最新のプラグインでMaven実行できることを確認できました。
ありがとうございました。
