### ISSUE TITLE
eclipse2023(Python Windows 64bit版)にて、一部外部ライブラリが正常にインストールできない

### ISSUE THREAD

**Issue by hana2sei** [cypher256/pleiades.io#148]
eclipse2023(Python Windows 64bit版)にて、外部ライブラリpsycopg2のインストールに失敗します。
matplotlibやscikit-learnは正常にインストールできます。
不思議なのが、eclipseの2022や2021では正常にインストールできるという点です。2023でなにか内部仕様に変更があったのでしょうか？

![image](https://github.com/cypher256/pleiades.io/assets/84162551/d42bdef3-d592-4763-8e18-2331d329c927)

以下エラー全文---------------------------------------------------->
Collecting psycopg2
  Using cached psycopg2-2.9.9.tar.gz (384 kB)
  Preparing metadata (setup.py): started
  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [51 lines of output]
  running egg_info
  creating C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-j88rp14g\psycopg2.egg-info
  writing C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-j88rp14g\psycopg2.egg-info\PKG-INFO
  writing dependency_links to C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-j88rp14g\psycopg2.egg-info\dependency_links.txt
  writing top-level names to C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-j88rp14g\psycopg2.egg-info\top_level.txt
  writing manifest file 'C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-j88rp14g\psycopg2.egg-info\SOURCES.txt'
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\user\AppData\Local\Temp\pip-install-4iwcr2uf\psycopg2_db2dc10d05f4454c8b62b8dbcfe7a802\setup.py", line 545, in <module>
      setup(name="psycopg2",
    File "C:\pleiades_p\python\3\lib\site-packages\setuptools\__init__.py", line 103, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\pleiades_p\python\3\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "C:\pleiades_p\python\3\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
      dist.run_commands()
    File "C:\pleiades_p\python\3\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "C:\pleiades_p\python\3\lib\site-packages\setuptools\dist.py", line 989, 
  Preparing metadata (setup.py): finished with status 'error'
in run_command
      super().run_command(command)
    File "C:\pleiades_p\python\3\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\pleiades_p\python\3\lib\site-packages\setuptools\command\egg_info.py", line 318, in run
      self.find_sources()
    File "C:\pleiades_p\python\3\lib\site-packages\setuptools\command\egg_info.py", line 326, in find_sources
      mm.run()
    File "C:\pleiades_p\python\3\lib\site-packages\setuptools\command\egg_info.py", line 548, in run
      self.add_defaults()
    File "C:\pleiades_p\python\3\lib\site-packages\setuptools\command\egg_info.py", line 586, in add_defaults
      sdist.add_defaults(self)
    File "C:\pleiades_p\python\3\lib\site-packages\setuptools\command\sdist.py", line 113, in add_defaults
      super().add_defaults()
    File "C:\pleiades_p\python\3\lib\site-packages\setuptools\_distutils\command\sdist.py", line 251, in add_defaults
      self._add_defaults_ext()
    File "C:\pleiades_p\python\3\lib\site-packages\setuptools\_distutils\command\sdist.py", line 335, in _add_defaults_ext
      build_ext = self.get_finalized_command('build_ext')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\pleiades_p\python\3\lib\site-packages\setuptools\_distutils\cmd.py", line 305, in get_finalized_command
      cmd_obj.ensure_finalized()
    File "C:\pleiades_p\python\3\lib\site-packages\setuptools\_distutils\cmd.py", line 111, in ensure_finalized
      self.finalize_options()
    File "C:\Users\user\AppData\Local\Temp\pip-install-4iwcr2uf\psycopg2_db2dc10d05f4454c8b62b8dbcfe7a802\setup.py", line 375, in finalize_options
      tokens = pg_config_helper.query("ldflags", empty_ok=True).split()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\user\AppData\Local\Temp\pip-install-4iwcr2uf\psycopg2_db2dc10d05f4454c8b62b8dbcfe7a802\setup.py", line 119, in query
      result = pg_config_process.stdout.decode().strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 0: invalid start byte
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
FINISHED

<---------------------------------------------------------------------

**Comment by cypher256** [comment]
Pleiades All in One の付属 Python バージョン
2022 -> 3.11
2023 -> 3.12

psycopg2 は現在 Python 3.12 対応中のようです。
https://github.com/psycopg/psycopg2/issues/1628

上記対応を待つか、python/3 ディレクトリを 2022 版のものに置き換えるかなどの対応が考えられます。

**Comment by hana2sei** [comment]
迅速な対応、および対応案のご提示ありがとうございます。
ライブラリ側の対応完了を待ちたいと思います。

**Comment by cypher256** [comment]
対応済みの psycopg2 がリリース済みのようなので、クローズします。
