### ISSUE TITLE
Eclipse Neonが起動しなくなりました

### ISSUE THREAD

**Issue by irobe** [cypher256/pleiades.io#21]
1年以上利用させていただいていますが、本日になって急に起動しなくなってしまいました。原因として何が考えられますでしょうか。

[eclipse\configuration\1560518522792.log]
!SESSION 2019-06-14 22:22:01.558 -----------------------------------------------
eclipse.buildId=4.6.3.M20170301-0400
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ja_JP
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product -clean

!ENTRY org.eclipse.equinox.ds 2 0 2019-06-14 22:22:39.409
!MESSAGE [SCR] バンドル com.genuitec.eclipse.theming.ui のコンポーネント有効化が 30000 ミリ秒で完了しませんでした 

!ENTRY org.eclipse.osgi 4 0 2019-06-14 22:22:56.910
!MESSAGE アプリケーション・エラー
!STACK 1
java.lang.NoSuchFieldError: url
	at org.eclipse.jface.resource.URLImageDescriptor.createImage(URLImageDescriptor.java:258)
	at org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:224)
	at org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:202)
	at org.eclipse.ui.internal.Workbench.initializeImages(Workbench.java:1898)
	at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:806)
	at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:160)
	at org.eclipse.ui.internal.ide.application.IDEApplication.createDisplay(IDEApplication.java:168)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:111)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

**Comment by cypher256** [comment]
以下を試してみてください。
3 は Eclipse のすべての設定が初期状態に戻るので、最終手段です。

1. eclipse.exe -clean.cmd で起動
2. configuration\jp.sourceforge.mergedoc.pleiades ディレクトリ削除したあとに起動
3. workspace をリネームしたあとに起動

**Comment by irobe** [comment]
ご回答ありがとうございます。
1～3いずれも起動しませんでした。

Pleiades環境を作り直す過程で、 Darkest Darkプラグインの[DevStyle Icon Designer]を
インストールすると起動しなくなることが分かりました。
正常に起動できるEclipse上で当該プラグインをアンインストールして解決しましたので報告します。

この度はご対応ありがとうございました。

**Comment by cypher256** [comment]
> Darkest Darkプラグインの[DevStyle Icon Designer]を
> インストールすると起動しなくなることが分かりました。

原因特定ありがとうございます。
修正する方向で進めたいと思います。

**Comment by cypher256** [comment]
DevStyle Icon Designer をインストールしても
現在、発生しないようなのでクローズします。
