### ISSUE TITLE
Androidstudio 4.0.2 で日本語化した後、起動できない

### ISSUE THREAD

**Issue by shixichann** [cypher256/pleiades.io#86]
下記環境で最新版の「Pleiades プラグイン・ダウンロード」を使い、Androidstudioを日本語化すると、起動出来ません。
（日本語化を無効にすると起動できます。）

Androidstudio 4.0.2
Windows 10 Pro　19042.1110

当方で調べた所、以下の様なエラーメッセージが出ています。

⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻
Exception in thread "main" java.lang.UnsupportedClassVersionError: jp/sourceforge/mergedoc/pleiades/Pleiades has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.findBootstrapClass(Native Method)
        at java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1009)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:408)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:406)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:304)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
FATAL ERROR in native method: processing of -javaagent failed
⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻

以前までは問題なく起動出来ていたのですが、
今回「Androidstudio」と「Pleiades プラグイン・ダウンロード」をアンインストールして、
もう一度ダウンロード・インストール（日本語化）した際に起きました。

エラーメッセージの内容から

＞2021.05.31　の変更
＞・高速化: 最小実行環境を Java 8 以降から Java 11 以降に変更 (Java 11 高速 API 使用)

この対応が行われたので、起動出来なくなっているのではないかと思っています。
お手数かと思いますが、 Java 8 で動く「Pleiades プラグイン・ダウンロード」（古いバージョン）の公開をお願い出来ませんか？

よろしくお願いします。

**Comment by cypher256** [comment]
詳細ありがとうございます。
Pleiades プラグイン・ダウンロード」に「アーカイブ: Java 8 対応版はこちら」を追加しました。
数時間後にミラーに反映されます。

**Comment by shixichann** [comment]
無事起動することが出来ました。
この日本語化プラグインには大変お世話になっており、ありがたく思っています。

もしよろしければ、最新版の方で最小実行環境をJAVA8に戻し、
JAVA11以上がインストールされている場合、「Java 11 高速 API 使用」というような挙動に変更して貰えると嬉しいです。

またお節介かもしれませんが、
「アーカイブ: Java 8 対応版」のファイル名にversion等の情報を追加されてはいかがですか？
（ダウンロードの際に最新版が同じ場所にあると上書きされそうになるので、ファイル名の変更のワンクッションが必要になります。「Pleiades All in One ダウンロード」の方では日付情報が追加されていますよね）

以上、よろしくお願いします。

この度は迅速な対応ありがとうございました。本当に困っていたのでたすかりました。

**Comment by cypher256** [comment]
無事動作したようで良かったです。
「アーカイブ: Java 8 対応版」にバージョン日付を足しました。
Java 11 と 8 の実行時挙動変更は Java 8 でビルドできないため、ちょっと困難です。
本件に関しては、解決済みとしてクローズします。

**Comment by shixichann** [comment]
ご対応ありがとうございます。
また、クローズ了解です。

「Androidstudio」を日本語化しようとした際、JAVA11で動作する方法が見つかっていません。
（ほんとこれ、どうすればいいでしょうかねorz）

このプラグインがそもそも「Androidstudio」を対象としていないのは分かっていますが、
”Androidstudio　日本語化”でヒットするサイトから紹介されているサイトはココになります。
「Androidstudio」の利用ユーザーも最新版と同様に使える様にして貰えると有難いです。

よろしくお願いします。
